if os.isfile("vendor/premake-vscode/vscode.lua") then
    require "vendor/premake-vscode/vscode"
end

newaction {
    trigger = "clion",
    description = "Generate CLion Makefile project settings and run configurations",
    execute = function()
        local rootDir = path.getabsolute(".")
        local ideaDir = path.join(rootDir, ".idea")
        local runDir = path.join(ideaDir, "runConfigurations")
        os.mkdir(ideaDir)
        os.mkdir(runDir)

        -- Tell CLion this is a Makefile project with our build args
        local makefileXml = path.join(ideaDir, "makefile.xml")
        local makefileFile = io.open(makefileXml, "w")
        makefileFile:write('<?xml version="1.0" encoding="UTF-8"?>\n')
        makefileFile:write('<project version="4">\n')
        makefileFile:write('  <component name="MakefileProjectSettings">\n')
        makefileFile:write('    <option name="linkedExternalProjectsSettings">\n')
        makefileFile:write('      <MakefileProjectSettings>\n')
        makefileFile:write('        <option name="externalProjectPath" value="$PROJECT_DIR$" />\n')
        makefileFile:write('        <option name="version" value="2" />\n')
        makefileFile:write('        <option name="makefilePath" value="$PROJECT_DIR$/Axiom/Makefile" />\n')
        makefileFile:write('        <option name="arguments" value="config=debug_26.1 -j8" />\n')
        makefileFile:write('      </MakefileProjectSettings>\n')
        makefileFile:write('    </option>\n')
        makefileFile:write('  </component>\n')
        makefileFile:write('</project>\n')
        makefileFile:close()
        print("Generated .idea/makefile.xml")

        -- Generate CMakeLists.txt for CLion native debug support
        local cmakeFile = io.open(path.join(rootDir, "CMakeLists.txt"), "w")
        cmakeFile:write('# Auto-generated by premake5 clion — do not edit manually\n')
        cmakeFile:write('cmake_minimum_required(VERSION 3.28)\n')
        cmakeFile:write('project(Axiom LANGUAGES CXX)\n\n')
        cmakeFile:write('set(CMAKE_CXX_STANDARD 23)\n')
        cmakeFile:write('set(CMAKE_CXX_STANDARD_REQUIRED ON)\n')
        cmakeFile:write('set(CMAKE_EXPORT_COMPILE_COMMANDS ON)\n\n')

        -- Glob sources
        cmakeFile:write('file(GLOB_RECURSE AXIOM_SOURCES\n')
        cmakeFile:write('    "${CMAKE_SOURCE_DIR}/Axiom/src/**.h"\n')
        cmakeFile:write('    "${CMAKE_SOURCE_DIR}/Axiom/src/**.cpp"\n')
        cmakeFile:write(')\n\n')

        -- Platform-specific sources (Axiom/Platform/<OS>/**.cpp)
        cmakeFile:write('if(APPLE)\n')
        cmakeFile:write('    file(GLOB_RECURSE AXIOM_PLATFORM_SOURCES\n')
        cmakeFile:write('        "${CMAKE_SOURCE_DIR}/Axiom/Platform/Macosx/**.cpp"\n')
        cmakeFile:write('        "${CMAKE_SOURCE_DIR}/Axiom/Platform/Macosx/**.h"\n')
        cmakeFile:write('    )\n')
        cmakeFile:write('elseif(WIN32)\n')
        cmakeFile:write('    file(GLOB_RECURSE AXIOM_PLATFORM_SOURCES\n')
        cmakeFile:write('        "${CMAKE_SOURCE_DIR}/Axiom/Platform/Windows/**.cpp"\n')
        cmakeFile:write('        "${CMAKE_SOURCE_DIR}/Axiom/Platform/Windows/**.h"\n')
        cmakeFile:write('    )\n')
        cmakeFile:write('elseif(UNIX)\n')
        cmakeFile:write('    file(GLOB_RECURSE AXIOM_PLATFORM_SOURCES\n')
        cmakeFile:write('        "${CMAKE_SOURCE_DIR}/Axiom/Platform/Linux/**.cpp"\n')
        cmakeFile:write('        "${CMAKE_SOURCE_DIR}/Axiom/Platform/Linux/**.h"\n')
        cmakeFile:write('    )\n')
        cmakeFile:write('endif()\n\n')

        cmakeFile:write('add_executable(Axiom ${AXIOM_SOURCES} ${AXIOM_PLATFORM_SOURCES})\n\n')

        -- PCH
        cmakeFile:write('target_precompile_headers(Axiom PRIVATE "${CMAKE_SOURCE_DIR}/Axiom/src/axpch.h")\n\n')

        -- Includes
        cmakeFile:write('target_include_directories(Axiom PRIVATE\n')
        cmakeFile:write('    "${CMAKE_SOURCE_DIR}/Axiom/src"\n')
        cmakeFile:write('    "${CMAKE_SOURCE_DIR}/Axiom/vendor/asio/asio/include"\n')
        cmakeFile:write('    "${CMAKE_SOURCE_DIR}/Axiom/vendor/json/include"\n')
        cmakeFile:write('    "${CMAKE_SOURCE_DIR}/Axiom/vendor/spdlog/include"\n')
        cmakeFile:write('    "${CMAKE_SOURCE_DIR}/Axiom/vendor/tomlplusplus/include"\n')
        cmakeFile:write('    "${CMAKE_SOURCE_DIR}/Axiom/vendor/yaml-cpp/include"\n')
        cmakeFile:write(')\n\n')

        -- Defines
        local commitCount = "0"
        local gitHandle = io.popen("git rev-list --count HEAD 2>/dev/null")
        if gitHandle then
            commitCount = gitHandle:read("*l") or "0"
            gitHandle:close()
        end

        cmakeFile:write('target_compile_definitions(Axiom PRIVATE\n')
        cmakeFile:write('    ASIO_STANDALONE\n')
        cmakeFile:write('    AX_COMMIT_COUNT=' .. commitCount .. '\n')
        cmakeFile:write(')\n\n')

        -- Per-config defines
        cmakeFile:write('target_compile_definitions(Axiom PRIVATE\n')
        cmakeFile:write('    $<$<CONFIG:Debug>:AX_DEBUG;AX_ENABLE_ASSERTS>\n')
        cmakeFile:write(')\n\n')

        -- Load packet IDs from JSON
        local function loadPacketJson(versionName)
            local result = {}
            local jsonPath = path.join(rootDir, "scripts", "packet-ids", versionName .. ".json")
            local file = io.open(jsonPath, "r")
            if not file then return result end
            local content = file:read("*a")
            file:close()
            local data = json.decode(content) or {}
            for stateName, directions in pairs(data) do
                local stateKey = stateName:upper()
                for dirName, packets in pairs(directions) do
                    local dirKey = dirName == "Serverbound" and "SB" or "CB"
                    for packetName, packetId in pairs(packets) do
                        local key = "PID_" .. stateKey .. "_" .. dirKey .. "_" .. packetName:upper()
                        table.insert(result, key .. "=" .. tostring(packetId))
                    end
                end
            end
            return result
        end

        local packetIds = loadPacketJson("26.1")
        if #packetIds > 0 then
            cmakeFile:write('# Packet ID defines for protocol 26.1\n')
            cmakeFile:write('target_compile_definitions(Axiom PRIVATE\n')
            cmakeFile:write('    AX_MINECRAFT_PROTOCOL=775\n')
            cmakeFile:write('    AX_MINECRAFT_VERSION="26.1"\n')
            for _, definition in ipairs(packetIds) do
                local key, value = definition:match("^(.-)=(.+)$")
                if key and value then
                    if string.find(key, "_CB_", 1, true) then
                        value = value .. ",PacketDirection::Clientbound"
                    elseif string.find(key, "_SB_", 1, true) then
                        value = value .. ",PacketDirection::Serverbound"
                    end
                    if string.find(key, "PID_HANDSHAKE", 1, true) then
                        value = value .. ",PacketState::Handshake"
                    elseif string.find(key, "PID_STATUS_", 1, true) then
                        value = value .. ",PacketState::Status"
                    elseif string.find(key, "PID_LOGIN_", 1, true) then
                        value = value .. ",PacketState::Login"
                    elseif string.find(key, "PID_CONFIGURATION_", 1, true) then
                        value = value .. ",PacketState::Configuration"
                    elseif string.find(key, "PID_PLAY_", 1, true) then
                        value = value .. ",PacketState::Play"
                    end
                    cmakeFile:write('    "' .. key .. '=' .. value .. '"\n')
                end
            end
            cmakeFile:write(')\n\n')
        end

        -- Platform-specific
        cmakeFile:write('if(APPLE)\n')
        cmakeFile:write('    target_compile_definitions(Axiom PRIVATE AX_PLATFORM_MACOS FMT_USE_CHAR8_T=0)\n')
        cmakeFile:write('    target_compile_options(Axiom PRIVATE -Wno-deprecated-declarations -Wall -Wextra -Wpedantic)\n')
        cmakeFile:write('    target_link_options(Axiom PRIVATE -stdlib=libc++)\n')
        cmakeFile:write('    find_package(OpenSSL REQUIRED)\n')
        cmakeFile:write('    find_package(ZLIB REQUIRED)\n')
        cmakeFile:write('    target_link_libraries(Axiom PRIVATE OpenSSL::SSL OpenSSL::Crypto ZLIB::ZLIB yaml-cpp)\n')
        cmakeFile:write('    target_include_directories(Axiom PRIVATE ${OPENSSL_INCLUDE_DIR})\n')
        cmakeFile:write('elseif(UNIX)\n')
        cmakeFile:write('    target_compile_definitions(Axiom PRIVATE AX_PLATFORM_LINUX)\n')
        cmakeFile:write('    target_compile_options(Axiom PRIVATE -Wall -Wextra -Wpedantic)\n')
        cmakeFile:write('    find_package(OpenSSL REQUIRED)\n')
        cmakeFile:write('    find_package(ZLIB REQUIRED)\n')
        cmakeFile:write('    target_link_libraries(Axiom PRIVATE OpenSSL::SSL OpenSSL::Crypto ZLIB::ZLIB yaml-cpp pthread)\n')
        cmakeFile:write('elseif(WIN32)\n')
        cmakeFile:write('    target_compile_definitions(Axiom PRIVATE AX_PLATFORM_WINDOWS)\n')
        cmakeFile:write('endif()\n\n')

        -- yaml-cpp subdirectory
        cmakeFile:write('add_subdirectory("${CMAKE_SOURCE_DIR}/Axiom/vendor/yaml-cpp" yaml-cpp)\n\n')

        -- Post-build: copy data
        cmakeFile:write('add_custom_command(TARGET Axiom POST_BUILD\n')
        cmakeFile:write('    COMMAND ${CMAKE_COMMAND} -E copy_directory\n')
        cmakeFile:write('    "${CMAKE_SOURCE_DIR}/data" "$<TARGET_FILE_DIR:Axiom>/data"\n')
        cmakeFile:write(')\n')

        cmakeFile:close()
        print("Generated CMakeLists.txt")

        -- Generate CLion CMake profiles for all configurations
        local cmakeXml = path.join(ideaDir, "cmake.xml")
        local cmakeXmlFile = io.open(cmakeXml, "w")
        cmakeXmlFile:write('<?xml version="1.0" encoding="UTF-8"?>\n')
        cmakeXmlFile:write('<project version="4">\n')
        cmakeXmlFile:write('  <component name="CMakeSharedSettings">\n')
        cmakeXmlFile:write('    <configurations>\n')

        local cmakeConfigs = {
            { name = "Release",       buildType = "Release" },
            { name = "Debug_26.1",    buildType = "Debug" },
            { name = "Release_26.1",  buildType = "Release" },
        }
        for _, cfg in ipairs(cmakeConfigs) do
            local buildDir = "bin/" .. cfg.name .. "_AARCH64/Axiom"
            cmakeXmlFile:write('      <configuration PROFILE_NAME="' .. cfg.name .. '" ENABLED="true" ')
            cmakeXmlFile:write('GENERATION_DIR="' .. buildDir .. '" ')
            cmakeXmlFile:write('CONFIG_NAME="' .. cfg.buildType .. '" />\n')
        end

        cmakeXmlFile:write('    </configurations>\n')
        cmakeXmlFile:write('  </component>\n')
        cmakeXmlFile:write('</project>\n')
        cmakeXmlFile:close()
        print("Generated .idea/cmake.xml")

        -- Generate run configurations with external terminal
        for _, cfg in ipairs(cmakeConfigs) do
            local safeName = cfg.name:gsub("%.", "_")
            local binDir = path.join(rootDir, "bin", cfg.name .. "_AARCH64", "Axiom")

            local xmlFile = io.open(path.join(runDir, "Axiom_" .. safeName .. ".xml"), "w")
            xmlFile:write('<component name="ProjectRunConfigurationManager">\n')
            xmlFile:write('  <configuration default="false" name="Axiom (' .. cfg.name .. ')" type="CMakeRunConfiguration" factoryName="Application" REDIRECT_INPUT="false" ELEVATE="false" USE_EXTERNAL_CONSOLE="false" EMULATE_TERMINAL="true" PASS_PARENT_ENVS_2="true">\n')
            xmlFile:write('    <option name="com.jetbrains.cidr.execution.CidrBuildBeforeRunTaskProvider$BuildBeforeRunTask" enabled="true" />\n')
            xmlFile:write('    <option name="PROGRAM_PARAMS" value="" />\n')
            xmlFile:write('    <option name="WORKING_DIR" value="' .. binDir .. '" />\n')
            xmlFile:write('    <option name="REDIRECT_INPUT_PATH" value="" />\n')
            xmlFile:write('    <EXECUTABLE_NAME value="Axiom" />\n')
            xmlFile:write('    <TARGET_NAME value="Axiom" />\n')
            xmlFile:write('    <CONFIG_NAME value="' .. cfg.buildType .. '" />\n')
            xmlFile:write('    <RUN_CONFIGURATION_PROFILE_NAME value="' .. cfg.name .. '" />\n')
            xmlFile:write('    <method v="2">\n')
            xmlFile:write('      <option name="com.jetbrains.cidr.execution.CidrBuildBeforeRunTaskProvider$BuildBeforeRunTask" enabled="true" />\n')
            xmlFile:write('    </method>\n')
            xmlFile:write('  </configuration>\n')
            xmlFile:write('</component>\n')
            xmlFile:close()
            print("Generated .idea/runConfigurations/Axiom_" .. safeName .. ".xml")
        end
    end
}

workspace "Axiom"
    architecture "ARM64"
    startproject "Axiom"

    configurations {
        "Debug", "Release",
        "Debug_26.1", "Release_26.1"
    }

outputdir = "%{cfg.buildcfg}_%{cfg.architecture}"

include "Axiom"
