package com.axiommc.api.block;

import java.util.HashMap;
import java.util.Map;

/** All vanilla 1.21 block types. {@link #UNKNOWN} is returned for unrecognised registry IDs. */
public enum Material {

    // --- Air
    AIR, CAVE_AIR, VOID_AIR,

    // --- Fluids
    WATER, LAVA,

    // --- Bedrock / Barrier
    BEDROCK, BARRIER, LIGHT, STRUCTURE_VOID, STRUCTURE_BLOCK, JIGSAW,

    // --- Dirt / Grass
    GRASS_BLOCK, DIRT, COARSE_DIRT, ROOTED_DIRT, PODZOL, MYCELIUM,
    DIRT_PATH, FARMLAND, MUD, PACKED_MUD, MUD_BRICKS,

    // --- Sand / Gravel
    SAND, RED_SAND, SUSPICIOUS_SAND, GRAVEL, SUSPICIOUS_GRAVEL,
    SOUL_SAND, SOUL_SOIL,

    // --- Stone
    STONE, GRANITE, POLISHED_GRANITE, DIORITE, POLISHED_DIORITE,
    ANDESITE, POLISHED_ANDESITE,
    COBBLESTONE, MOSSY_COBBLESTONE,
    SMOOTH_STONE,
    STONE_BRICKS, MOSSY_STONE_BRICKS, CRACKED_STONE_BRICKS, CHISELED_STONE_BRICKS,
    INFESTED_STONE, INFESTED_COBBLESTONE, INFESTED_STONE_BRICKS,
    INFESTED_MOSSY_STONE_BRICKS, INFESTED_CRACKED_STONE_BRICKS, INFESTED_CHISELED_STONE_BRICKS,
    BRICKS,

    // --- Deepslate
    DEEPSLATE, COBBLED_DEEPSLATE, POLISHED_DEEPSLATE,
    DEEPSLATE_BRICKS, CRACKED_DEEPSLATE_BRICKS,
    DEEPSLATE_TILES, CRACKED_DEEPSLATE_TILES,
    CHISELED_DEEPSLATE, REINFORCED_DEEPSLATE,
    INFESTED_DEEPSLATE,

    // --- Tuff
    TUFF, POLISHED_TUFF, TUFF_BRICKS, CHISELED_TUFF, CHISELED_TUFF_BRICKS,

    // --- Calcite / Dripstone
    CALCITE, DRIPSTONE_BLOCK, POINTED_DRIPSTONE,

    // --- Amethyst
    AMETHYST_BLOCK, BUDDING_AMETHYST,
    AMETHYST_CLUSTER, LARGE_AMETHYST_BUD, MEDIUM_AMETHYST_BUD, SMALL_AMETHYST_BUD,

    // --- Sandstone
    SANDSTONE, CHISELED_SANDSTONE, CUT_SANDSTONE, SMOOTH_SANDSTONE,
    RED_SANDSTONE, CHISELED_RED_SANDSTONE, CUT_RED_SANDSTONE, SMOOTH_RED_SANDSTONE,

    // --- Ores
    COAL_ORE, DEEPSLATE_COAL_ORE,
    IRON_ORE, DEEPSLATE_IRON_ORE,
    COPPER_ORE, DEEPSLATE_COPPER_ORE,
    GOLD_ORE, DEEPSLATE_GOLD_ORE, NETHER_GOLD_ORE,
    REDSTONE_ORE, DEEPSLATE_REDSTONE_ORE,
    EMERALD_ORE, DEEPSLATE_EMERALD_ORE,
    LAPIS_ORE, DEEPSLATE_LAPIS_ORE,
    DIAMOND_ORE, DEEPSLATE_DIAMOND_ORE,
    NETHER_QUARTZ_ORE, ANCIENT_DEBRIS,

    // --- Ore / Raw Blocks
    COAL_BLOCK, IRON_BLOCK, RAW_IRON_BLOCK,
    GOLD_BLOCK, RAW_GOLD_BLOCK,
    DIAMOND_BLOCK, EMERALD_BLOCK, LAPIS_BLOCK, REDSTONE_BLOCK,
    COPPER_BLOCK, RAW_COPPER_BLOCK,
    EXPOSED_COPPER, WEATHERED_COPPER, OXIDIZED_COPPER,
    CUT_COPPER, EXPOSED_CUT_COPPER, WEATHERED_CUT_COPPER, OXIDIZED_CUT_COPPER,
    CHISELED_COPPER, EXPOSED_CHISELED_COPPER, WEATHERED_CHISELED_COPPER, OXIDIZED_CHISELED_COPPER,
    COPPER_GRATE, EXPOSED_COPPER_GRATE, WEATHERED_COPPER_GRATE, OXIDIZED_COPPER_GRATE,
    COPPER_BULB, EXPOSED_COPPER_BULB, WEATHERED_COPPER_BULB, OXIDIZED_COPPER_BULB,
    NETHERITE_BLOCK,

    // --- Quartz
    QUARTZ_BLOCK, CHISELED_QUARTZ_BLOCK, QUARTZ_PILLAR, SMOOTH_QUARTZ, QUARTZ_BRICKS,

    // --- Oak
    OAK_LOG, STRIPPED_OAK_LOG, OAK_WOOD, STRIPPED_OAK_WOOD, OAK_PLANKS,
    OAK_SLAB, OAK_STAIRS, OAK_FENCE, OAK_FENCE_GATE,
    OAK_DOOR, OAK_TRAPDOOR, OAK_BUTTON, OAK_PRESSURE_PLATE,
    OAK_SIGN, OAK_WALL_SIGN, OAK_HANGING_SIGN, OAK_WALL_HANGING_SIGN,
    OAK_LEAVES, OAK_SAPLING,

    // --- Spruce
    SPRUCE_LOG, STRIPPED_SPRUCE_LOG, SPRUCE_WOOD, STRIPPED_SPRUCE_WOOD, SPRUCE_PLANKS,
    SPRUCE_SLAB, SPRUCE_STAIRS, SPRUCE_FENCE, SPRUCE_FENCE_GATE,
    SPRUCE_DOOR, SPRUCE_TRAPDOOR, SPRUCE_BUTTON, SPRUCE_PRESSURE_PLATE,
    SPRUCE_SIGN, SPRUCE_WALL_SIGN, SPRUCE_HANGING_SIGN, SPRUCE_WALL_HANGING_SIGN,
    SPRUCE_LEAVES, SPRUCE_SAPLING,

    // --- Birch
    BIRCH_LOG, STRIPPED_BIRCH_LOG, BIRCH_WOOD, STRIPPED_BIRCH_WOOD, BIRCH_PLANKS,
    BIRCH_SLAB, BIRCH_STAIRS, BIRCH_FENCE, BIRCH_FENCE_GATE,
    BIRCH_DOOR, BIRCH_TRAPDOOR, BIRCH_BUTTON, BIRCH_PRESSURE_PLATE,
    BIRCH_SIGN, BIRCH_WALL_SIGN, BIRCH_HANGING_SIGN, BIRCH_WALL_HANGING_SIGN,
    BIRCH_LEAVES, BIRCH_SAPLING,

    // --- Jungle
    JUNGLE_LOG, STRIPPED_JUNGLE_LOG, JUNGLE_WOOD, STRIPPED_JUNGLE_WOOD, JUNGLE_PLANKS,
    JUNGLE_SLAB, JUNGLE_STAIRS, JUNGLE_FENCE, JUNGLE_FENCE_GATE,
    JUNGLE_DOOR, JUNGLE_TRAPDOOR, JUNGLE_BUTTON, JUNGLE_PRESSURE_PLATE,
    JUNGLE_SIGN, JUNGLE_WALL_SIGN, JUNGLE_HANGING_SIGN, JUNGLE_WALL_HANGING_SIGN,
    JUNGLE_LEAVES, JUNGLE_SAPLING,

    // --- Acacia
    ACACIA_LOG, STRIPPED_ACACIA_LOG, ACACIA_WOOD, STRIPPED_ACACIA_WOOD, ACACIA_PLANKS,
    ACACIA_SLAB, ACACIA_STAIRS, ACACIA_FENCE, ACACIA_FENCE_GATE,
    ACACIA_DOOR, ACACIA_TRAPDOOR, ACACIA_BUTTON, ACACIA_PRESSURE_PLATE,
    ACACIA_SIGN, ACACIA_WALL_SIGN, ACACIA_HANGING_SIGN, ACACIA_WALL_HANGING_SIGN,
    ACACIA_LEAVES, ACACIA_SAPLING,

    // --- Dark Oak
    DARK_OAK_LOG, STRIPPED_DARK_OAK_LOG, DARK_OAK_WOOD, STRIPPED_DARK_OAK_WOOD, DARK_OAK_PLANKS,
    DARK_OAK_SLAB, DARK_OAK_STAIRS, DARK_OAK_FENCE, DARK_OAK_FENCE_GATE,
    DARK_OAK_DOOR, DARK_OAK_TRAPDOOR, DARK_OAK_BUTTON, DARK_OAK_PRESSURE_PLATE,
    DARK_OAK_SIGN, DARK_OAK_WALL_SIGN, DARK_OAK_HANGING_SIGN, DARK_OAK_WALL_HANGING_SIGN,
    DARK_OAK_LEAVES, DARK_OAK_SAPLING,

    // --- Cherry
    CHERRY_LOG, STRIPPED_CHERRY_LOG, CHERRY_WOOD, STRIPPED_CHERRY_WOOD, CHERRY_PLANKS,
    CHERRY_SLAB, CHERRY_STAIRS, CHERRY_FENCE, CHERRY_FENCE_GATE,
    CHERRY_DOOR, CHERRY_TRAPDOOR, CHERRY_BUTTON, CHERRY_PRESSURE_PLATE,
    CHERRY_SIGN, CHERRY_WALL_SIGN, CHERRY_HANGING_SIGN, CHERRY_WALL_HANGING_SIGN,
    CHERRY_LEAVES, CHERRY_SAPLING,

    // --- Pale Oak
    PALE_OAK_LOG, STRIPPED_PALE_OAK_LOG, PALE_OAK_WOOD, STRIPPED_PALE_OAK_WOOD, PALE_OAK_PLANKS,
    PALE_OAK_SLAB, PALE_OAK_STAIRS, PALE_OAK_FENCE, PALE_OAK_FENCE_GATE,
    PALE_OAK_DOOR, PALE_OAK_TRAPDOOR, PALE_OAK_BUTTON, PALE_OAK_PRESSURE_PLATE,
    PALE_OAK_SIGN, PALE_OAK_WALL_SIGN, PALE_OAK_HANGING_SIGN, PALE_OAK_WALL_HANGING_SIGN,
    PALE_OAK_LEAVES, PALE_OAK_SAPLING, PALE_MOSS_BLOCK, PALE_MOSS_CARPET,
    PALE_HANGING_MOSS, OPEN_EYEBLOSSOM, CLOSED_EYEBLOSSOM,

    // --- Mangrove
    MANGROVE_LOG, STRIPPED_MANGROVE_LOG, MANGROVE_WOOD, STRIPPED_MANGROVE_WOOD, MANGROVE_PLANKS,
    MANGROVE_SLAB, MANGROVE_STAIRS, MANGROVE_FENCE, MANGROVE_FENCE_GATE,
    MANGROVE_DOOR, MANGROVE_TRAPDOOR, MANGROVE_BUTTON, MANGROVE_PRESSURE_PLATE,
    MANGROVE_SIGN, MANGROVE_WALL_SIGN, MANGROVE_HANGING_SIGN, MANGROVE_WALL_HANGING_SIGN,
    MANGROVE_LEAVES, MANGROVE_PROPAGULE, MANGROVE_ROOTS, MUDDY_MANGROVE_ROOTS,

    // --- Bamboo
    BAMBOO_BLOCK, STRIPPED_BAMBOO_BLOCK, BAMBOO_PLANKS, BAMBOO_MOSAIC,
    BAMBOO_SLAB, BAMBOO_STAIRS, BAMBOO_MOSAIC_SLAB, BAMBOO_MOSAIC_STAIRS,
    BAMBOO_FENCE, BAMBOO_FENCE_GATE, BAMBOO_DOOR, BAMBOO_TRAPDOOR,
    BAMBOO_BUTTON, BAMBOO_PRESSURE_PLATE,
    BAMBOO_SIGN, BAMBOO_WALL_SIGN, BAMBOO_HANGING_SIGN, BAMBOO_WALL_HANGING_SIGN,
    BAMBOO, BAMBOO_SAPLING,

    // --- Crimson (Nether)
    CRIMSON_STEM, STRIPPED_CRIMSON_STEM, CRIMSON_HYPHAE, STRIPPED_CRIMSON_HYPHAE, CRIMSON_PLANKS,
    CRIMSON_SLAB, CRIMSON_STAIRS, CRIMSON_FENCE, CRIMSON_FENCE_GATE,
    CRIMSON_DOOR, CRIMSON_TRAPDOOR, CRIMSON_BUTTON, CRIMSON_PRESSURE_PLATE,
    CRIMSON_SIGN, CRIMSON_WALL_SIGN, CRIMSON_HANGING_SIGN, CRIMSON_WALL_HANGING_SIGN,
    CRIMSON_ROOTS, CRIMSON_FUNGUS, WEEPING_VINES, WEEPING_VINES_PLANT,

    // --- Warped (Nether)
    WARPED_STEM, STRIPPED_WARPED_STEM, WARPED_HYPHAE, STRIPPED_WARPED_HYPHAE, WARPED_PLANKS,
    WARPED_SLAB, WARPED_STAIRS, WARPED_FENCE, WARPED_FENCE_GATE,
    WARPED_DOOR, WARPED_TRAPDOOR, WARPED_BUTTON, WARPED_PRESSURE_PLATE,
    WARPED_SIGN, WARPED_WALL_SIGN, WARPED_HANGING_SIGN, WARPED_WALL_HANGING_SIGN,
    WARPED_ROOTS, WARPED_FUNGUS, TWISTING_VINES, TWISTING_VINES_PLANT, NETHER_SPROUTS,

    // --- Other Leaves / Plants
    AZALEA_LEAVES, FLOWERING_AZALEA_LEAVES, AZALEA, FLOWERING_AZALEA,
    SHORT_GRASS, TALL_GRASS, FERN, LARGE_FERN, DEAD_BUSH,
    DANDELION, TORCHFLOWER, POPPY, BLUE_ORCHID, ALLIUM, AZURE_BLUET,
    RED_TULIP, ORANGE_TULIP, WHITE_TULIP, PINK_TULIP, OXEYE_DAISY,
    CORNFLOWER, LILY_OF_THE_VALLEY, WITHER_ROSE,
    SUNFLOWER, LILAC, ROSE_BUSH, PEONY, PINK_PETALS,
    SPORE_BLOSSOM, BIG_DRIPLEAF, BIG_DRIPLEAF_STEM, SMALL_DRIPLEAF,
    MOSS_BLOCK, MOSS_CARPET,
    SUGAR_CANE, CACTUS, PUMPKIN, CARVED_PUMPKIN, JACK_O_LANTERN,
    MELON, ATTACHED_PUMPKIN_STEM, PUMPKIN_STEM, ATTACHED_MELON_STEM, MELON_STEM,
    VINE, GLOW_LICHEN, HANGING_ROOTS,
    LILY_PAD, KELP, KELP_PLANT, SEA_GRASS, TALL_SEAGRASS,
    SEAGRASS, CORAL_BLOCK, DEAD_CORAL_BLOCK,
    TUBE_CORAL_BLOCK, BRAIN_CORAL_BLOCK, BUBBLE_CORAL_BLOCK, FIRE_CORAL_BLOCK, HORN_CORAL_BLOCK,
    DEAD_TUBE_CORAL_BLOCK, DEAD_BRAIN_CORAL_BLOCK, DEAD_BUBBLE_CORAL_BLOCK,
    DEAD_FIRE_CORAL_BLOCK, DEAD_HORN_CORAL_BLOCK,
    TUBE_CORAL, BRAIN_CORAL, BUBBLE_CORAL, FIRE_CORAL, HORN_CORAL,
    DEAD_TUBE_CORAL, DEAD_BRAIN_CORAL, DEAD_BUBBLE_CORAL, DEAD_FIRE_CORAL, DEAD_HORN_CORAL,
    TUBE_CORAL_FAN, BRAIN_CORAL_FAN, BUBBLE_CORAL_FAN, FIRE_CORAL_FAN, HORN_CORAL_FAN,
    DEAD_TUBE_CORAL_FAN, DEAD_BRAIN_CORAL_FAN, DEAD_BUBBLE_CORAL_FAN,
    DEAD_FIRE_CORAL_FAN, DEAD_HORN_CORAL_FAN,
    TUBE_CORAL_WALL_FAN, BRAIN_CORAL_WALL_FAN, BUBBLE_CORAL_WALL_FAN,
    FIRE_CORAL_WALL_FAN, HORN_CORAL_WALL_FAN,
    DEAD_TUBE_CORAL_WALL_FAN, DEAD_BRAIN_CORAL_WALL_FAN, DEAD_BUBBLE_CORAL_WALL_FAN,
    DEAD_FIRE_CORAL_WALL_FAN, DEAD_HORN_CORAL_WALL_FAN,
    SEA_PICKLE, SPONGE, WET_SPONGE,

    // ── Mushrooms ─────────────────────────────────────────────────────────────
    RED_MUSHROOM, BROWN_MUSHROOM,
    RED_MUSHROOM_BLOCK, BROWN_MUSHROOM_BLOCK, MUSHROOM_STEM,

    // ── Wool ──────────────────────────────────────────────────────────────────
    WHITE_WOOL, ORANGE_WOOL, MAGENTA_WOOL, LIGHT_BLUE_WOOL, YELLOW_WOOL,
    LIME_WOOL, PINK_WOOL, GRAY_WOOL, LIGHT_GRAY_WOOL, CYAN_WOOL,
    PURPLE_WOOL, BLUE_WOOL, BROWN_WOOL, GREEN_WOOL, RED_WOOL, BLACK_WOOL,

    // ── Carpet ────────────────────────────────────────────────────────────────
    WHITE_CARPET, ORANGE_CARPET, MAGENTA_CARPET, LIGHT_BLUE_CARPET, YELLOW_CARPET,
    LIME_CARPET, PINK_CARPET, GRAY_CARPET, LIGHT_GRAY_CARPET, CYAN_CARPET,
    PURPLE_CARPET, BLUE_CARPET, BROWN_CARPET, GREEN_CARPET, RED_CARPET, BLACK_CARPET,

    // ── Concrete ──────────────────────────────────────────────────────────────
    WHITE_CONCRETE, ORANGE_CONCRETE, MAGENTA_CONCRETE, LIGHT_BLUE_CONCRETE, YELLOW_CONCRETE,
    LIME_CONCRETE, PINK_CONCRETE, GRAY_CONCRETE, LIGHT_GRAY_CONCRETE, CYAN_CONCRETE,
    PURPLE_CONCRETE, BLUE_CONCRETE, BROWN_CONCRETE, GREEN_CONCRETE, RED_CONCRETE, BLACK_CONCRETE,

    // ── Concrete Powder ───────────────────────────────────────────────────────
    WHITE_CONCRETE_POWDER, ORANGE_CONCRETE_POWDER, MAGENTA_CONCRETE_POWDER,
    LIGHT_BLUE_CONCRETE_POWDER, YELLOW_CONCRETE_POWDER, LIME_CONCRETE_POWDER,
    PINK_CONCRETE_POWDER, GRAY_CONCRETE_POWDER, LIGHT_GRAY_CONCRETE_POWDER,
    CYAN_CONCRETE_POWDER, PURPLE_CONCRETE_POWDER, BLUE_CONCRETE_POWDER,
    BROWN_CONCRETE_POWDER, GREEN_CONCRETE_POWDER, RED_CONCRETE_POWDER, BLACK_CONCRETE_POWDER,

    // ── Terracotta ────────────────────────────────────────────────────────────
    TERRACOTTA,
    WHITE_TERRACOTTA, ORANGE_TERRACOTTA, MAGENTA_TERRACOTTA, LIGHT_BLUE_TERRACOTTA,
    YELLOW_TERRACOTTA, LIME_TERRACOTTA, PINK_TERRACOTTA, GRAY_TERRACOTTA,
    LIGHT_GRAY_TERRACOTTA, CYAN_TERRACOTTA, PURPLE_TERRACOTTA, BLUE_TERRACOTTA,
    BROWN_TERRACOTTA, GREEN_TERRACOTTA, RED_TERRACOTTA, BLACK_TERRACOTTA,

    // ── Glazed Terracotta ─────────────────────────────────────────────────────
    WHITE_GLAZED_TERRACOTTA, ORANGE_GLAZED_TERRACOTTA, MAGENTA_GLAZED_TERRACOTTA,
    LIGHT_BLUE_GLAZED_TERRACOTTA, YELLOW_GLAZED_TERRACOTTA, LIME_GLAZED_TERRACOTTA,
    PINK_GLAZED_TERRACOTTA, GRAY_GLAZED_TERRACOTTA, LIGHT_GRAY_GLAZED_TERRACOTTA,
    CYAN_GLAZED_TERRACOTTA, PURPLE_GLAZED_TERRACOTTA, BLUE_GLAZED_TERRACOTTA,
    BROWN_GLAZED_TERRACOTTA, GREEN_GLAZED_TERRACOTTA, RED_GLAZED_TERRACOTTA,
    BLACK_GLAZED_TERRACOTTA,

    // ── Glass ─────────────────────────────────────────────────────────────────
    GLASS, TINTED_GLASS,
    WHITE_STAINED_GLASS, ORANGE_STAINED_GLASS, MAGENTA_STAINED_GLASS,
    LIGHT_BLUE_STAINED_GLASS, YELLOW_STAINED_GLASS, LIME_STAINED_GLASS,
    PINK_STAINED_GLASS, GRAY_STAINED_GLASS, LIGHT_GRAY_STAINED_GLASS,
    CYAN_STAINED_GLASS, PURPLE_STAINED_GLASS, BLUE_STAINED_GLASS,
    BROWN_STAINED_GLASS, GREEN_STAINED_GLASS, RED_STAINED_GLASS, BLACK_STAINED_GLASS,
    GLASS_PANE,
    WHITE_STAINED_GLASS_PANE, ORANGE_STAINED_GLASS_PANE, MAGENTA_STAINED_GLASS_PANE,
    LIGHT_BLUE_STAINED_GLASS_PANE, YELLOW_STAINED_GLASS_PANE, LIME_STAINED_GLASS_PANE,
    PINK_STAINED_GLASS_PANE, GRAY_STAINED_GLASS_PANE, LIGHT_GRAY_STAINED_GLASS_PANE,
    CYAN_STAINED_GLASS_PANE, PURPLE_STAINED_GLASS_PANE, BLUE_STAINED_GLASS_PANE,
    BROWN_STAINED_GLASS_PANE, GREEN_STAINED_GLASS_PANE, RED_STAINED_GLASS_PANE,
    BLACK_STAINED_GLASS_PANE,

    // ── Prismarine ────────────────────────────────────────────────────────────
    PRISMARINE, PRISMARINE_BRICKS, DARK_PRISMARINE, SEA_LANTERN,

    // ── Nether Brick ─────────────────────────────────────────────────────────
    NETHER_BRICKS, CRACKED_NETHER_BRICKS, CHISELED_NETHER_BRICKS, RED_NETHER_BRICKS,
    NETHER_BRICK_FENCE, NETHER_BRICK_SLAB, NETHER_BRICK_STAIRS, NETHER_BRICK_WALL,
    RED_NETHER_BRICK_SLAB, RED_NETHER_BRICK_STAIRS, RED_NETHER_BRICK_WALL,

    // ── Blackstone ────────────────────────────────────────────────────────────
    BLACKSTONE, POLISHED_BLACKSTONE, CHISELED_POLISHED_BLACKSTONE, GILDED_BLACKSTONE,
    POLISHED_BLACKSTONE_BRICKS, CRACKED_POLISHED_BLACKSTONE_BRICKS,
    POLISHED_BLACKSTONE_SLAB, POLISHED_BLACKSTONE_STAIRS, POLISHED_BLACKSTONE_WALL,
    POLISHED_BLACKSTONE_BRICK_SLAB, POLISHED_BLACKSTONE_BRICK_STAIRS,
    POLISHED_BLACKSTONE_BRICK_WALL, BLACKSTONE_SLAB, BLACKSTONE_STAIRS, BLACKSTONE_WALL,
    POLISHED_BLACKSTONE_BUTTON, POLISHED_BLACKSTONE_PRESSURE_PLATE,

    // ── Basalt ────────────────────────────────────────────────────────────────
    BASALT, POLISHED_BASALT, SMOOTH_BASALT,

    // ── Obsidian ──────────────────────────────────────────────────────────────
    OBSIDIAN, CRYING_OBSIDIAN,

    // ── Ice ───────────────────────────────────────────────────────────────────
    ICE, PACKED_ICE, BLUE_ICE, SNOW_BLOCK, SNOW, POWDER_SNOW,
    FROSTED_ICE,

    // ── End ───────────────────────────────────────────────────────────────────
    END_STONE, END_STONE_BRICKS, END_PORTAL, END_PORTAL_FRAME, END_GATEWAY,
    PURPUR_BLOCK, PURPUR_PILLAR, PURPUR_SLAB, PURPUR_STAIRS,
    CHORUS_PLANT, CHORUS_FLOWER,

    // ── Crops / Farming ───────────────────────────────────────────────────────
    WHEAT, CARROTS, POTATOES, BEETROOTS, TORCHFLOWER_CROP, PITCHER_CROP, PITCHER_PLANT,
    NETHER_WART,

    // ── Functional / Utility ─────────────────────────────────────────────────
    CRAFTING_TABLE, FURNACE, BLAST_FURNACE, SMOKER,
    CHEST, TRAPPED_CHEST, BARREL, ENDER_CHEST,
    SHULKER_BOX,
    WHITE_SHULKER_BOX, ORANGE_SHULKER_BOX, MAGENTA_SHULKER_BOX, LIGHT_BLUE_SHULKER_BOX,
    YELLOW_SHULKER_BOX, LIME_SHULKER_BOX, PINK_SHULKER_BOX, GRAY_SHULKER_BOX,
    LIGHT_GRAY_SHULKER_BOX, CYAN_SHULKER_BOX, PURPLE_SHULKER_BOX, BLUE_SHULKER_BOX,
    BROWN_SHULKER_BOX, GREEN_SHULKER_BOX, RED_SHULKER_BOX, BLACK_SHULKER_BOX,
    ANVIL, CHIPPED_ANVIL, DAMAGED_ANVIL,
    ENCHANTING_TABLE, BOOKSHELF, CHISELED_BOOKSHELF, DECORATED_POT,
    BREWING_STAND, CAULDRON, LAVA_CAULDRON, WATER_CAULDRON, POWDER_SNOW_CAULDRON,
    BEACON, CONDUIT,
    JUKEBOX, NOTE_BLOCK, BELL,
    LECTERN, LOOM, CARTOGRAPHY_TABLE, FLETCHING_TABLE, SMITHING_TABLE, GRINDSTONE,
    STONECUTTER, COMPOSTER, SMOKER_BLOCK,
    BEE_NEST, BEEHIVE,
    LODESTONE, RESPAWN_ANCHOR,
    CRAFTER,
    VAULT, TRIAL_SPAWNER,

    // ── Redstone ──────────────────────────────────────────────────────────────
    REDSTONE_WIRE, REDSTONE_TORCH, REDSTONE_WALL_TORCH, REDSTONE_LAMP,
    LEVER, STONE_BUTTON, POLISHED_BLACKSTONE_BUTTON_BLOCK,
    STONE_PRESSURE_PLATE, LIGHT_WEIGHTED_PRESSURE_PLATE, HEAVY_WEIGHTED_PRESSURE_PLATE,
    REPEATER, COMPARATOR, DROPPER, DISPENSER, PISTON, STICKY_PISTON, PISTON_HEAD,
    MOVING_PISTON, OBSERVER, HOPPER, TRIPWIRE, TRIPWIRE_HOOK,
    TNT, TARGET,

    // ── Lighting ──────────────────────────────────────────────────────────────
    TORCH, WALL_TORCH, SOUL_TORCH, SOUL_WALL_TORCH, GLOWSTONE,
    LANTERN, SOUL_LANTERN, SHROOMLIGHT, SEA_LANTERN_BLOCK,
    GLOW_ITEM_FRAME, END_ROD,
    FIRE, SOUL_FIRE,

    // ── Ore-adjacent / Nether ─────────────────────────────────────────────────
    NETHERRACK, NETHER_WART_BLOCK, WARPED_WART_BLOCK, MAGMA_BLOCK,
    GLOWSTONE_DUST_BLOCK,

    // ── Slabs (stone variants) ────────────────────────────────────────────────
    STONE_SLAB, SMOOTH_STONE_SLAB, SANDSTONE_SLAB, CUT_SANDSTONE_SLAB,
    COBBLESTONE_SLAB, BRICK_SLAB, STONE_BRICK_SLAB, MUD_BRICK_SLAB,
    MOSSY_COBBLESTONE_SLAB, MOSSY_STONE_BRICK_SLAB,
    GRANITE_SLAB, POLISHED_GRANITE_SLAB, DIORITE_SLAB, POLISHED_DIORITE_SLAB,
    ANDESITE_SLAB, POLISHED_ANDESITE_SLAB,
    RED_SANDSTONE_SLAB, CUT_RED_SANDSTONE_SLAB, SMOOTH_RED_SANDSTONE_SLAB,
    PRISMARINE_SLAB, PRISMARINE_BRICK_SLAB, DARK_PRISMARINE_SLAB,
    END_STONE_BRICK_SLAB, COBBLED_DEEPSLATE_SLAB, POLISHED_DEEPSLATE_SLAB,
    DEEPSLATE_BRICK_SLAB, DEEPSLATE_TILE_SLAB, TUFF_SLAB, POLISHED_TUFF_SLAB, TUFF_BRICK_SLAB,

    // ── Stairs (stone variants) ───────────────────────────────────────────────
    COBBLESTONE_STAIRS, STONE_STAIRS, SMOOTH_STONE_STAIRS, SANDSTONE_STAIRS,
    MOSSY_COBBLESTONE_STAIRS, STONE_BRICK_STAIRS, MOSSY_STONE_BRICK_STAIRS,
    BRICK_STAIRS, MUD_BRICK_STAIRS, GRANITE_STAIRS, POLISHED_GRANITE_STAIRS,
    DIORITE_STAIRS, POLISHED_DIORITE_STAIRS, ANDESITE_STAIRS, POLISHED_ANDESITE_STAIRS,
    RED_SANDSTONE_STAIRS, SMOOTH_SANDSTONE_STAIRS, SMOOTH_RED_SANDSTONE_STAIRS,
    PRISMARINE_STAIRS, PRISMARINE_BRICK_STAIRS, DARK_PRISMARINE_STAIRS,
    END_STONE_BRICK_STAIRS,
    COBBLED_DEEPSLATE_STAIRS, POLISHED_DEEPSLATE_STAIRS,
    DEEPSLATE_BRICK_STAIRS, DEEPSLATE_TILE_STAIRS,
    TUFF_STAIRS, POLISHED_TUFF_STAIRS, TUFF_BRICK_STAIRS,

    // ── Walls ─────────────────────────────────────────────────────────────────
    COBBLESTONE_WALL, MOSSY_COBBLESTONE_WALL, STONE_BRICK_WALL, MOSSY_STONE_BRICK_WALL,
    BRICK_WALL, PRISMARINE_WALL, GRANITE_WALL, DIORITE_WALL, ANDESITE_WALL,
    SANDSTONE_WALL, RED_SANDSTONE_WALL, END_STONE_BRICK_WALL,
    COBBLED_DEEPSLATE_WALL, POLISHED_DEEPSLATE_WALL, DEEPSLATE_BRICK_WALL,
    DEEPSLATE_TILE_WALL, TUFF_WALL, POLISHED_TUFF_WALL, TUFF_BRICK_WALL,
    MUD_BRICK_WALL,

    // ── Iron / Metal Blocks ───────────────────────────────────────────────────
    IRON_BARS, IRON_DOOR, IRON_TRAPDOOR, HEAVY_CORE,

    // ── Misc ──────────────────────────────────────────────────────────────────
    BONE_BLOCK, HAY_BLOCK, DRIED_KELP_BLOCK, HONEYCOMB_BLOCK,
    MELON_BLOCK, PUMPKIN_BLOCK,
    SLIME_BLOCK, HONEY_BLOCK, MAGNET_BLOCK,
    NETHER_PORTAL, COBWEB, LADDER, SCAFFOLDING,
    DRAGON_EGG, DRAGON_HEAD, DRAGON_WALL_HEAD,
    PLAYER_HEAD, PLAYER_WALL_HEAD, CREEPER_HEAD, CREEPER_WALL_HEAD,
    ZOMBIE_HEAD, ZOMBIE_WALL_HEAD, SKELETON_SKULL, SKELETON_WALL_SKULL,
    WITHER_SKELETON_SKULL, WITHER_SKELETON_WALL_SKULL, PIGLIN_HEAD, PIGLIN_WALL_HEAD,

    // ── Fallback ──────────────────────────────────────────────────────────────
    UNKNOWN;

    // ── Lookup ────────────────────────────────────────────────────────────────

    private static final Map<String, Material> BY_ID;

    static {
        Map<String, Material> map = new HashMap<>();
        for (Material m : values()) {
            if (m != UNKNOWN) {
                map.put("minecraft:" + m.name().toLowerCase(), m);
            }
        }
        BY_ID = Map.copyOf(map);
    }

    /** Namespaced block identifier, e.g. {@code "minecraft:stone"}. */
    public String id() {
        return this == UNKNOWN ? "minecraft:unknown" : "minecraft:" + name().toLowerCase();
    }

    /** Returns the enum constant for the given namespaced registry ID, or {@link #UNKNOWN}. */
    public static Material of(String id) {
        return BY_ID.getOrDefault(id, UNKNOWN);
    }
}
