#include "DedicatedProperties.h"

#include "Axiom/Core/Log.h"

#include <fstream>
#include <sstream>

namespace Axiom {

void DedicatedProperties::Load(const std::string& path) {
	m_Properties.clear();

	std::ifstream file(path);
	if (!file.good()) {
		AX_CORE_INFO("No server.properties found at {}", path);
		return;
	}

	std::string line;
	while (std::getline(file, line)) {
		if (line.empty() || line[0] == '#')
			continue;

		auto delimiter = line.find('=');
		if (delimiter == std::string::npos)
			continue;

		auto key = line.substr(0, delimiter);
		auto value = line.substr(delimiter + 1);
		m_Properties[key] = value;
	}

	AX_CORE_INFO("Loaded {} properties from {}", m_Properties.size(), path);
}

void DedicatedProperties::Save(const std::string& path) const {
	std::ofstream file(path);
	if (!file.good()) {
		AX_CORE_ERROR("Failed to write server.properties to {}", path);
		return;
	}

	file << "#Minecraft server properties\n";
	file << "#(auto-generated by Axiom)\n";

	for (auto& [key, value] : m_Properties)
		file << key << "=" << value << "\n";

	AX_CORE_INFO("Saved server.properties to {}", path);
}

void DedicatedProperties::ImportInto(ServerConfig& /*config*/) const {
	// DedicatedProperties import is a no-op when TOML is
	// the canonical source. This method exists so that
	// users migrating from vanilla can drop in their
	// server.properties and have the values picked up
	// on first boot before server.toml is written.
	//
	// Since ServerConfig reads TOML, the import would need
	// to modify the TOML table directly -- which requires
	// the table to be mutable. For now, log a notice.
	AX_CORE_INFO("server.properties import is a future migration feature");
}

void DedicatedProperties::ExportFrom(const ServerConfig& config) {
	m_Properties.clear();

	m_Properties["server-ip"] = config.BindAddress();
	m_Properties["server-port"] = std::to_string(config.Port());
	m_Properties["online-mode"] = config.OnlineMode() ? "true" : "false";
	m_Properties["motd"] = config.Motd();
	m_Properties["max-players"] = std::to_string(config.MaxPlayers());
	m_Properties["view-distance"] = std::to_string(config.ViewDistance());
	m_Properties["simulation-distance"] = std::to_string(config.SimulationDistance());
	m_Properties["spawn-protection"] = std::to_string(config.SpawnProtection());
	m_Properties["white-list"] = config.WhitelistEnabled() ? "true" : "false";
	m_Properties["difficulty"] = config.Difficulty();
	m_Properties["gamemode"] = config.GameMode();
	m_Properties["pvp"] = config.Pvp() ? "true" : "false";
	m_Properties["enable-command-block"] = config.EnableCommandBlock() ? "true" : "false";
	m_Properties["level-seed"] = config.LevelSeed();
	m_Properties["level-type"] = config.LevelType();
	m_Properties["network-compression-threshold"] = std::to_string(config.CompressionThreshold());
}

std::string DedicatedProperties::Get(const std::string& key, const std::string& fallback) const {
	auto iterator = m_Properties.find(key);
	if (iterator != m_Properties.end())
		return iterator->second;
	return fallback;
}

void DedicatedProperties::Set(const std::string& key, const std::string& value) {
	m_Properties[key] = value;
}

}
