local function split(value, separator)
    if separator == nil then
        separator = "%s"
    end
    local result = {}
    for segment in string.gmatch(value, "([^" .. separator .. "]+)") do
        table.insert(result, segment)
    end
    return result
end

local function loadPacketIds(versionName)
    local result = {}

    local function loadJsonFile(path)
        local file = io.open(path, "r")
        if not file then return nil end
        local content = file:read("*a")
        file:close()
        return json.decode(content)
    end

    local versionPath = "../scripts/packet-ids/" .. versionName .. ".json"
    local versionData = loadJsonFile(versionPath) or {}

    local function normalize(key)
        key = key:gsub("-", "_"):upper()
        if key == "SERVERBOUND" then return "SB"
        elseif key == "CLIENTBOUND" then return "CB"
        else return key end
    end

    local function flattenTable(table, prefix)
        for key, value in pairs(table) do
            local newPrefix = prefix and (prefix .. "_" .. normalize(key)) or normalize(key)
            if type(value) == "table" then
                flattenTable(value, newPrefix)
            else
                if type(value) == "string" then
                    value = '"' .. value .. '"'
                elseif type(value) == "boolean" then
                    value = value and "1" or "0"
                end
                ::continue::
                result[#result + 1] = "PID_" .. newPrefix .. "=" .. tostring(value)
            end
        end
    end

    flattenTable(versionData, nil)
    return result
end

local function registerServerPackets()
    local files = os.matchfiles("src/Axiom/Network/Packet/**/Serverbound/**.h")

    local imports = {}
    local definitions = {}

    for _, file in ipairs(files) do
        table.insert(imports, tostring(string.gsub(file, "src/", "")))

        local relative = string.gsub(file, "src/Axiom/Network/Packet/", "")
        local parts = split(relative, "/")
        -- parts[1] = state dir (e.g. "Play")
        -- parts[2] = "Serverbound"
        -- parts[3] = filename (e.g. "KeepAlive.h")
        if #parts >= 3 then
            local className = string.gsub(parts[3], "%.h$", "") .. "Packet"
            local namespacePath = "Axiom::" .. parts[1] .. "::" .. parts[2] .. "::" .. className
            table.insert(definitions, namespacePath)
        end
    end

    return { imports, definitions }
end

local function generatePacketFactory()
    local items = registerServerPackets()
    local imports = items[1]
    local definitions = items[2]

    local headerPath = "src/Axiom/Network/Packet/RegisterPackets.generated.h"
    local sourcePath = "src/Axiom/Network/Packet/RegisterPackets.generated.cpp"

    -- Header
    local headerFile = io.open(headerPath, "w")
    headerFile:write("#pragma once\n")
    headerFile:write("#include \"Axiom/Core/Base.h\"\n\n")
    for _, import in ipairs(imports) do
        headerFile:write("#include \"" .. import .. "\"\n")
    end
    headerFile:close()

    -- Source
    local sourceFile = io.open(sourcePath, "w")
    sourceFile:write("#include \"axpch.h\"\n")
    sourceFile:write("#include \"RegisterPackets.generated.h\"\n\n")
    sourceFile:write("#include \"Axiom/Network/Packet/PacketFactory.h\"\n\n")
    sourceFile:write("namespace Axiom {\n\n")
    sourceFile:write("    void PacketFactory::RegisterAll() {\n")
    for _, definition in ipairs(definitions) do
        sourceFile:write("        RegisterDefaultParser<" .. definition .. ">();\n")
    end
    sourceFile:write("    }\n\n")
    sourceFile:write("}\n")
    sourceFile:close()
end

-- ----- Helper: add per-version defines --------------------------

local function addVersionDefine(version, name, value)
    filter("configurations:Debug_" .. version)
        defines { name .. "=" .. value }

    filter("configurations:Release_" .. version)
        defines { name .. "=" .. value }
end

-- ----- Protocol versions ----------------------------------------

local protocolVersions = {
    ["26.1"] = 775,
}

-- ----- Generate packet ID header (for IDE resolution) -----------

local function generatePacketIdHeader()
    local headerPath = "src/Axiom/Network/Packet/PacketIds.generated.h"
    local headerFile = io.open(headerPath, "w")
    headerFile:write("// Auto-generated by premake5.lua — do not edit\n")
    headerFile:write("#pragma once\n\n")
    headerFile:write("#include \"Axiom/Network/Packet/PacketDirection.h\"\n")
    headerFile:write("#include \"Axiom/Network/Packet/PacketState.h\"\n\n")
    headerFile:write("#ifndef PID_UNKNOWN\n")
    headerFile:write("#define PID_UNKNOWN 65535\n")

    for version, _ in pairs(protocolVersions) do
        local packetIds = loadPacketIds(version)
        for _, definition in ipairs(packetIds) do
            local key, value = definition:match("^(.-)=(.+)$")
            if key and value then
                local fullValue = value
                if string.find(key, "_CB_", 1, true) then
                    fullValue = fullValue .. ",PacketDirection::Clientbound"
                elseif string.find(key, "_SB_", 1, true) then
                    fullValue = fullValue .. ",PacketDirection::Serverbound"
                end

                if string.find(key, "PID_HANDSHAKE", 1, true) then
                    fullValue = fullValue .. ",PacketState::Handshake"
                elseif string.find(key, "PID_STATUS_", 1, true) then
                    fullValue = fullValue .. ",PacketState::Status"
                elseif string.find(key, "PID_LOGIN_", 1, true) then
                    fullValue = fullValue .. ",PacketState::Login"
                elseif string.find(key, "PID_CONFIGURATION_", 1, true) then
                    fullValue = fullValue .. ",PacketState::Configuration"
                elseif string.find(key, "PID_PLAY_", 1, true) then
                    fullValue = fullValue .. ",PacketState::Play"
                end

                if string.find(fullValue, "-1", 1, true) then
                    fullValue = "PID_UNKNOWN," .. fullValue
                    fullValue = string.gsub(fullValue, "-1,", "")
                end

                headerFile:write("#ifndef " .. key .. "\n")
                headerFile:write("#define " .. key .. " " .. fullValue .. "\n")
                headerFile:write("#endif\n")
            end
        end
    end

    headerFile:write("#endif\n")
    headerFile:close()
end

-- ----- Generate packet factory ----------------------------------

generatePacketFactory()
generatePacketIdHeader()

project "Axiom"
	kind "ConsoleApp"
	language "C++"
	staticruntime "off"

	cppdialect "C++23"

	pchheader "src/axpch.h"
    pchsource "src/axpch.cpp"

    targetdir ("%{wks.location}/bin/" .. outputdir .. "/%{prj.name}")
	objdir ("%{wks.location}/bin-int/" .. outputdir .. "/%{prj.name}")

    files {
        "src/**.h",
        "src/**.cpp",
    }

	vpaths 
	{
        ["Header Files/*"] = { "src/**.h",  "src/**.hpp" },
        ["Source Files/*"] = { "src/**.c", "src/**.cpp" },
    }

    includedirs {
        "src",
        "vendor/asio/asio/include",
        "vendor/json/include",
        "vendor/spdlog/include",
        "vendor/tomlplusplus/include",
        "vendor/yaml-cpp/include",
        "/opt/homebrew/opt/openssl/include",
    }

    filter "action:xcode4"
        xcodebuildsettings {
            ["ALWAYS_SEARCH_USER_PATHS"] = "YES",
        }
    filter {}

    -- Force ANSI color output in Xcode console
    debugenvs {
        "TERM=xterm-256color",
    }

    defines {
        "ASIO_STANDALONE",
    }

    links {
        "yaml-cpp",
    }

    for version, protocolId in pairs(protocolVersions) do
        addVersionDefine(version, "PID_UNKNOWN", "65535")

        local packetIds = loadPacketIds(version)
        for _, definition in ipairs(packetIds) do
            local key, value = definition:match("^(.-)=(.+)$")
            if key and value then
                if string.find(key, "_CB_", 1, true) then
                    value = value .. ",PacketDirection::Clientbound"
                elseif string.find(key, "_SB_", 1, true) then
                    value = value .. ",PacketDirection::Serverbound"
                end

                if string.find(key, "PID_HANDSHAKE", 1, true) then
                    value = value .. ",PacketState::Handshake"
                elseif string.find(key, "PID_STATUS_", 1, true) then
                    value = value .. ",PacketState::Status"
                elseif string.find(key, "PID_LOGIN_", 1, true) then
                    value = value .. ",PacketState::Login"
                elseif string.find(key, "PID_CONFIGURATION_", 1, true) then
                    value = value .. ",PacketState::Configuration"
                elseif string.find(key, "PID_PLAY_", 1, true) then
                    value = value .. ",PacketState::Play"
                end

                if string.find(value, "-1", 1, true) then
                    value = "PID_UNKNOWN," .. value
                    value = string.gsub(value, "-1,", "")
                end

                addVersionDefine(version, key, value)
            end
        end

        addVersionDefine(version, "AX_MINECRAFT_PROTOCOL", protocolId)
        addVersionDefine(version, "AX_MINECRAFT_VERSION", "\"" .. version .. "\"")
    end

    filter "system:macosx"
        defines {
            "AX_PLATFORM_MACOS",
            "FMT_USE_CHAR8_T=0",
        }
        buildoptions {
            "-std=c++23",
            "-stdlib=libc++",
            "-Wno-deprecated-declarations",
            "-Wall",
            "-Wextra",
            "-Wpedantic",
        }
        linkoptions {
            "-stdlib=libc++",
        }
        libdirs {
            "/opt/homebrew/lib",
            "/opt/homebrew/opt/openssl/lib",
        }
        includedirs {
            "/opt/homebrew/opt/openssl/include",
        }
        links {
            "ssl",
            "crypto",
            "z",
        }

    filter "system:linux"
        defines { "AX_PLATFORM_LINUX" }
        buildoptions {
            "-Wall",
            "-Wextra",
            "-Wpedantic",
        }
        links {
            "ssl",
            "crypto",
            "z",
            "pthread",
        }

    filter "system:windows"

    filter "configurations:Debug*"
        defines { "AX_DEBUG", "AX_ENABLE_ASSERTS" }
        runtime "Debug"
        symbols "on"
        optimize "off"

    filter "configurations:Release*"

    filter {}
    postbuildcommands {
        "{COPYDIR} %{wks.location}/data %{cfg.targetdir}/data",
    }