#!/usr/bin/env bash
#
# Bumps the persistent AX_BUILD_COUNT used in the debug prompt.
# Increments on every debug build; resets to 0 whenever the git HEAD
# changes (i.e. a new commit lands). Writes the value into a generated
# header that Application.cpp includes under #ifdef AX_DEBUG.
#
# Usage: bump-build-count.sh <workspace-root>

set -e

WORKSPACE_ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
STATE_COMMIT="$WORKSPACE_ROOT/.buildcount-commit"
STATE_COUNT="$WORKSPACE_ROOT/.buildcount"
HEADER_FILE="$WORKSPACE_ROOT/Axiom/src/Axiom/Core/BuildCount.generated.h"

CURRENT_COMMIT="$(git -C "$WORKSPACE_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"

STORED_COMMIT=""
STORED_COUNT=0
if [ -f "$STATE_COMMIT" ]; then
	STORED_COMMIT="$(cat "$STATE_COMMIT")"
fi
if [ -f "$STATE_COUNT" ]; then
	STORED_COUNT="$(cat "$STATE_COUNT")"
fi

if [ "$CURRENT_COMMIT" = "$STORED_COMMIT" ]; then
	NEW_COUNT=$((STORED_COUNT + 1))
else
	NEW_COUNT=0
fi

printf '%s' "$CURRENT_COMMIT" > "$STATE_COMMIT"
printf '%s' "$NEW_COUNT" > "$STATE_COUNT"

mkdir -p "$(dirname "$HEADER_FILE")"
cat > "$HEADER_FILE" <<EOF
// Auto-generated by scripts/bump-build-count.sh — do not edit, do not commit
#pragma once
#define AX_BUILD_COUNT $NEW_COUNT
EOF
