#pragma once

#include "Axiom/Core/Base.h"
#include "Axiom/Network/Connection.h"
#include "Axiom/Network/Packet/Packet.h"
#include "Axiom/Network/Packet/PacketState.h"
#include "Axiom/Network/Packet/PacketDirection.h"

#include <cstdint>
#include <functional>
#include <unordered_map>

namespace Axiom {

    class Connection;
    class PacketContext;
    class NetworkBuffer;

    using PacketHandlerFn = std::function<void(
        const Ref<Connection>&, PacketContext&, NetworkBuffer&)>;

    class PacketFactory {
    public:
        /**
         * Look up the handler for (state, packetId) and
         * invoke it, fully parsing and handling the packet.
         */
        static void DispatchPacket(PacketState state,
                                   int32_t packetId,
                                   const Ref<Connection>& connection,
                                   PacketContext& context,
                                   NetworkBuffer& buffer);

        /**
         * Register a packet type with automatic parse-and-
         * handle behaviour derived from its CRTP metadata.
         */
        template<typename T>
        static void RegisterDefaultParser() {
            if (T::GetPacketIdStatic() == PID_UNKNOWN)
                return;

            constexpr auto state = T::GetStateStatic();
            constexpr auto packetId = T::GetPacketIdStatic();

            s_Handlers[state][packetId] =
                [](const Ref<Connection>& connection,
                   PacketContext& context,
                   NetworkBuffer& buffer) {
                    T packet;
                    auto chain = packet.HandleImpl(connection, context, buffer);
                    if (chain) {
                        for (auto& response : *chain) {
                            if (response->GetDirection() != PacketDirection::Clientbound)
                                continue;
                            NetworkBuffer payload;
                            response->Write(payload);
                            connection->SendRawPacket(
                                response->GetPacketId(), payload);
                            response->OnSent(connection);
                        }
                    }
                };
        }

        /**
         * Populate s_Handlers with every known packet type.
         * Implementation is auto-generated by premake5 into
         * RegisterPackets.generated.cpp.
         */
        static void RegisterAll();

    private:
        static std::unordered_map<
            PacketState,
            std::unordered_map<int32_t, PacketHandlerFn>> s_Handlers;
    };

}
